# Generated by Django 5.2 on 2025-05-15 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vizhinjamport', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vizhinjamport.login')),
            ],
        ),
    ]
