# Generated by Django 5.2 on 2025-05-19 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vizhinjamport', '0005_tender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='Company_name',
            new_name='company_name',
        ),
    ]
