# Generated by Django 5.2 on 2025-05-19 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vizhinjamport', '0006_rename_company_name_company_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='Reg_no',
            new_name='reg_no',
        ),
        migrations.RenameField(
            model_name='tender',
            old_name='Reg_no',
            new_name='reg_no',
        ),
    ]
