# Generated by Django 5.2 on 2025-05-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizhinjamport', '0007_rename_reg_no_company_reg_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='usertype',
            field=models.CharField(default='public', max_length=100),
            preserve_default=False,
        ),
    ]
