# Generated by Django 5.2 on 2025-05-27 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizhinjamport', '0009_ship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productcategory', models.CharField(max_length=100)),
                ('productname', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('recipientname', models.CharField(max_length=100)),
                ('recipientaddress', models.CharField(max_length=100)),
                ('recipientcontact', models.IntegerField()),
                ('recipientemail', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('currentdate', models.DateField(auto_now_add=True)),
                ('publicid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vizhinjamport.user')),
                ('shipid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vizhinjamport.ship')),
            ],
        ),
    ]
