# Generated by Django 5.2 on 2025-05-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizhinjamport', '0010_export'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
