# Generated by Django 5.2 on 2025-05-29 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizhinjamport', '0011_login_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productcategory', models.CharField(max_length=100)),
                ('productname', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('tax', models.FloatField()),
                ('currentdate', models.DateField(auto_now_add=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vizhinjamport.company')),
            ],
        ),
    ]
