# Generated by Django 5.2 on 2025-05-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizhinjamport', '0012_exportcharges'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='paymentstaus',
            field=models.IntegerField(default=0),
        ),
    ]
