# Generated by Django 5.2 on 2025-05-31 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizhinjamport', '0013_export_paymentstaus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholder', models.CharField(max_length=100)),
                ('cardno', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('expirydate', models.IntegerField()),
                ('expiryyear', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('currentdate', models.DateField(auto_now_add=True)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vizhinjamport.login')),
            ],
        ),
    ]
