# Generated by Django 5.2 on 2025-06-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizhinjamport', '0014_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='export',
            old_name='paymentstaus',
            new_name='paymentstatus',
        ),
        migrations.AddField(
            model_name='export',
            name='cancelstatus',
            field=models.IntegerField(default=0),
        ),
    ]
