# Generated by Django 5.2 on 2025-06-06 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizhinjamport', '0015_rename_paymentstaus_export_paymentstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('complaint', models.TextField(max_length=200)),
                ('reply', models.TextField(null=True)),
                ('currentdate', models.DateField(auto_now_add=True)),
                ('export_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vizhinjamport.export')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vizhinjamport.user')),
            ],
        ),
    ]
