# Generated by Django 5.2 on 2025-06-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizhinjamport', '0016_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='image',
            field=models.FileField(default='complaints/a.jpg', upload_to='complaints/'),
            preserve_default=False,
        ),
    ]
