# Generated by Django 5.2 on 2025-06-07 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vizhinjamport', '0017_complaint_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tender',
            new_name='Contractor',
        ),
    ]
