# Generated by Django 5.2 on 2025-06-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizhinjamport', '0018_rename_tender_contractor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('discription', models.TextField(max_length=200)),
                ('amount', models.IntegerField()),
                ('no_of_month', models.IntegerField()),
                ('last_date_apply', models.DateField()),
                ('currentdate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
