# Generated by Django 5.2 on 2025-06-07 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizhinjamport', '0019_tender'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedTender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('currentdate', models.DateField(auto_now_add=True)),
                ('contractor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vizhinjamport.contractor')),
                ('tender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vizhinjamport.tender')),
            ],
        ),
    ]
