# Generated by Django 5.2 on 2025-06-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizhinjamport', '0020_appliedtender'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='refundstatus',
            field=models.IntegerField(default=0),
        ),
    ]
