# Generated by Django 5.2 on 2025-06-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizhinjamport', '0021_export_refundstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedtender',
            name='applystatus',
            field=models.IntegerField(default=0),
        ),
    ]
