# Generated by Django 5.2 on 2025-06-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizhinjamport', '0022_appliedtender_applystatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('discription', models.TextField(max_length=100)),
                ('lastdateapply', models.DateField()),
                ('currentdate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
