# Generated by Django 5.2 on 2025-06-18 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizhinjamport', '0023_tempjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=100)),
                ('documents', models.FileField(upload_to='documents/')),
                ('currentdate', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vizhinjamport.tempjob')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vizhinjamport.user')),
            ],
        ),
    ]
