# Generated by Django 5.2 on 2025-06-21 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizhinjamport', '0026_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentlocation', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('ship_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vizhinjamport.ship')),
            ],
        ),
    ]
