# Generated by Django 5.2 on 2025-06-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizhinjamport', '0027_shiptracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportcharges',
            name='tax',
            field=models.IntegerField(),
        ),
    ]
