# Generated by Django 5.2 on 2025-06-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizhinjamport', '0028_alter_exportcharges_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
