# Generated by Django 5.2 on 2025-06-28 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizhinjamport', '0029_alter_export_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField()),
                ('reply', models.TextField()),
                ('currentdate', models.DateField(auto_now_add=True)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vizhinjamport.login')),
            ],
        ),
    ]
