# Generated by Django 5.2 on 2025-09-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizhinjamport', '0030_allcomplaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='exportstatus',
            field=models.IntegerField(default=0),
        ),
    ]
