# Generated by Django 5.2 on 2025-09-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizhinjamport', '0031_export_exportstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiptracking',
            name='ship_status',
            field=models.IntegerField(default=0),
        ),
    ]
