# Generated by Django 5.2 on 2025-09-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizhinjamport', '0032_shiptracking_ship_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempjob',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
