# Generated by Django 5.2 on 2025-09-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizhinjamport', '0033_tempjob_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='discription',
            field=models.TextField(max_length=247),
        ),
        migrations.AlterField(
            model_name='tempjob',
            name='discription',
            field=models.TextField(max_length=247),
        ),
    ]
